version: '14.0'
services:
  odoo_14:
    image: odoo:14.0
    depends_on:
      - db_14
    ports:
      - "8069:8069"
    volumes:
      - odoo_14-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./dev_addons:/mnt/dev-addons
    environment:
      - HOST=db_14

  db_14:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
volumes:
  odoo_14-web-data: