version: '16.0'
services:
  odoo_16:
    image: odoo:16.0
    depends_on:
      - db_16
    ports:
      - "8069:8069"
    volumes:
      - odoo_16-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./dev_addons:/mnt/dev-addons
    environment:
      - HOST=db_16

  db_16:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
volumes:
  odoo_16-web-data: